## Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

def numpy_array(N):
    array = np.arange(N, -1, -1)
    return array

numpy_array(10)
#numpy_array(1)
#numpy_array(-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

## Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [2]:
D = np.diag(numpy_array(10))
print(D)

[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]


In [3]:
D.trace()

55

## Задание 3
Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [4]:
from numpy import linalg

a = [4, 2, 1]
b = [1, 3, 0]
c = [0, 5, 4]
A = np.matrix((a,b,c))
B = [4, 12, -3]
linalg.solve(A, B)

array([ 0.46666667,  3.84444444, -5.55555556])

## Задание 4
Вам подаются на вход два вектора a и b в трехмерном пространстве.Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy.

In [5]:
a = np.random.rand(3,)
b = np.random.rand(3,)
print(f"a={a}")
print(f"b={b}")


np.dot(a,b)

a=[0.05129467 0.19557553 0.17386945]
b=[0.48188993 0.78139119 0.68174514]


0.29607402734682453